### ISSUE TITLE
Requests sent to gitlab.com even when configured to run on locally hosted instance

### ISSUE THREAD

**Issue by ghsa-retrieval** [SonarSource-Demos/sonar-golc#1]
When configuring the sonar-golc for a locally hosted Gitlab instance, it will still send requests to gitlab.com when attempting to retrieve branches, which has two effects:

1. The tool does not work and reports 0 LoC
2. It leaks project structures and access tokens to gitlab.com

Example from the job log, where `internal-group` and `internal-repo` are placeholders for real names:

> 🔎 Analysis of Repos ...
>  Waiting for workers...
> --❌ Stack: gogit.Getrepos Git Branch refs/heads/main - authentication required-- Source: [https://gitlab-ci-token:[MASKED]@gitlab.com/internal-group/internal-repo.git](https://gitlab-ci-token:%5BMASKED%5D@gitlab.com/internal-group/internal-repo.git) -lstat /tmp/gcloc-extract-4f4db85749eb20d4177dfc1f77de2707: no such file or directory

The config.json looks like this, with `example.com` being a placeholder for the actual locally hosted Gitlab instance and `${GROUP_TOKEN}` and `${GROUP_NAME}` being placeholders for `envsubst`.

```
{
    "platforms": {
      "Gitlab": {
        "Users": "internal-user",
        "AccessToken": "${GROUP_TOKEN}",
        "Organization":"${GROUP_NAME}",
        "DevOps": "gitlab",
        "Project": "",
        "Repos": "",
        "Branch": "",
        "DefaultBranch": false,
        "Url": "https://example.com/",
        "Apiver": "v4",
        "Baseapi": "api/",
        "Protocol": "https",
        "FileExclusion":".cloc_gitlab_ignore",
        "Period":-1,
        "Factor":33,
        "Multithreading":true,
        "Stats": false,
        "Workers": 50,
        "NumberWorkerRepos":50
      }
    }
  }
```

**Comment by emmanuel-colussi-sonarsource** [comment]
Hi @ghsa-retrieval  , thank you for your detailed feedback regarding the use of sonar-golc with your locally hosted GitLab instance. We understand the issues you've encountered and appreciate you bringing them to our attention.

Currently, the version of sonar-golc you are using only supports the cloud version of GitLab. We acknowledge that this results in requests being sent to gitlab.com, which can cause functionality issues and potential data security concerns as you described.
We are pleased to inform you that support for locally hosted GitLab instances will be included in an upcoming version of sonar-golc. This update will also include improvements to mask access tokens and project structures, thereby enhancing security and confidentiality.
We appreciate your patience and understanding. In the meantime, we recommend keeping an eye on release announcements to be informed as soon as this feature becomes available.
